name: Publish

on:
    create:
        branches:
            - release/**

jobs:

    test:

        runs-on: ubuntu-latest

        env: 
            OpenWeather_Token: ${{secrets.TOKEN}}
            OpenWeather_Timeout: 30

        steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 6.x.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build --verbosity normal
        
    publish:

        needs: test

        env:
            BUILD_CONFIG: 'Release'

        runs-on: ubuntu-latest

        steps:

        - uses: actions/checkout@v2

        - name: .NET Setup
          uses : actions/setup-dotnet@v2
          with:
            dotnet-version: 6.x.x

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5

        - name: Get Version
          run: |
            Write-Host $Env:GITHUB_REF
            $version = $Env:GITHUB_REF.Split('/')[1]
            echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          shell: pwsh

        - name: Dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration $BUILD_CONFIG --no-restore -p:Version=$BUILD_VERSION

        - name: Publish
          run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_KEY}}